# Generated by Django 5.1.6 on 2025-03-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroNutrientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentry',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macroNutrientApp.food'),
        ),
    ]
